#!/bin/bash
cd /mnt/volume2/Torrents/Completed
unrar e -o- -r *.rar
rm -r */*.r*
rm -r */*.nfo
rm -r */*.sfv
rm -r *.r*
rm -r *.nfo
rm -r *.sfv
rm -r *sample*
rm -r */*sample*
rm -r */*/*sample*
rmdir -p */*/*/*/*
rmdir -p */*/*/*
rmdir -p */*/*
rmdir -p */*
rmdir -p *