core_packages:
  - git-core
  - openssh-server
  - unrar-free
  - apache2
  - samba

git_scripts_repo: https://github.com/DirtyCajunRice/scripts.git

git_scripts_repo_destination: /opt/DirtyCajunRice
