---

- hosts: cluster
  remote_user: nick
  become: yes

  tasks:
  - name: Installing Core Packages
    apt: 
      name:
      - git-core
      - openssh-server
      - unrar-free
      - apache2
      - samba
      state=present
      update_cache=yes
      cache_valid_time=3600