#!/bin/bash
currentip=$(curl -s ifconfig.co)
currententry=$(grep home zonefile)
newentry=$(awk -v format="%-8s %-3s %-2s %s\n" \
               -v publicip="$currentip" \
               'BEGIN { printf format, "home", "IN", "A", publicip }')
oldip=${currententry/^[^[:digit:]]*/}
currentserial=$(grep -oE "[[:digit:]]{10}" zonefile)
currentserialinc=${currentserial#?????????}
serialpre=$(date +%Y%m%d)
currentserialpre=${currentserial%??}

if ! [[ "$currentip" == "$oldip" ]]; then
    if [[ $serialpre < $currentserialpre ]]; then
        newserial="${serialpre}01"
    else
        ((currentserialinc++))
        newserial=${serialpre}${currentserialinc}
    fi
    sed -ie "s/$currentserial/$newserial/" -e "s/$currententry/$newentry/" zonefile
    rndc reload
    bindlog=$(grep bzdell.com /var/log/messages | tail -n5)
    echo "Your public IP address has changed from $oldip to $currentip. See below Bind log:
    $bindlog" | \
    mail -s "Your IP address has changed!!" root@localhost
fi
