#!/bin/bash
domain='tld.com'
zonefile='/etc/bind/zones/db.tld.com'
currentip=$(/tmp/currentdynamic.ip)
currententry=$(grep home $zonefile)
newentry=$(awk -v format="%-8s %-3s %-2s %s\n" \
               -v publicip="$currentip" \
               'BEGIN { printf format, "home", "IN", "A", publicip }')
oldip=${currententry/^[^[:digit:]]*/}
currentserial=$(grep -oE "[[:digit:]]{10}" $zonefile)
currentserialinc=${currentserial#?????????}
serialpre=$(date +%Y%m%d)
currentserialpre=${currentserial%??}

if ! [[ "$currentip" == "$oldip" ]]; then
    if [[ $serialpre < $currentserialpre ]]; then
        newserial="${serialpre}01"
    else
        ((currentserialinc++))
        newserial=${serialpre}${currentserialinc}
    fi
    sed -ie "s/$currentserial/$newserial/" -e "s/$currententry/$newentry/" $zonefile
    rndc reload
    bindlog=$(grep $domain /var/log/messages | tail -n5)
    echo "Your dynamic IP address has changed from $oldip to $currentip. See below Bind log:
    $bindlog" | \
    mail -s "Your dynamic IP address has changed!!" yourname@google.com
fi
